In [1]:
import numpy as np
from numpy import random 


arr1 = np.random.randint(50,size=(4,4))
print(arr1)
# part a.
print("Mean : ",arr1.mean(axis=1))
print("Standard Deviation : ",arr1.std(axis=1))
print("Variance : ",arr1.var(axis=1))



[[32 24 23 38]
 [21 35 33  9]
 [32 17 38 47]
 [25 46  2 26]]
Mean :  [29.25 24.5  33.5  24.75]
Standard Deviation :  [ 6.13901458 10.42832681 10.92016483 15.5784306 ]
Variance :  [ 37.6875 108.75   119.25   242.6875]


In [2]:
# part b.
B = np.array([56,48,22,41,78,91,24,46,8,33])

print(B)
B = np.sort(B)
print(B)

for i in range(len(B)):
    print("Index of", B[i], "is: ", i)


[56 48 22 41 78 91 24 46  8 33]
[ 8 22 24 33 41 46 48 56 78 91]
Index of 8 is:  0
Index of 22 is:  1
Index of 24 is:  2
Index of 33 is:  3
Index of 41 is:  4
Index of 46 is:  5
Index of 48 is:  6
Index of 56 is:  7
Index of 78 is:  8
Index of 91 is:  9


In [3]:
# part c.
m=int(input("Enter Number of Row  : "))
n=int(input("Enter Number of Column  : "))

mn = np.random.randint(50,size=(m,n))
print(mn)
print("Shape of mn is: ",mn.shape)
print("Data Type of mn is: ",mn.dtype)
print("Type of mn is: ",type(mn))

nm = mn.reshape(n,m)
print("\nReshaped array nm is: ",nm)
print("Shape of nm is: ",nm.shape)
print("Data Type of nm is: ",nm.dtype)
print("Type of mn is: ",type(nm))


Enter Number of Row  :  4
Enter Number of Column  :  5


[[ 9  3 41  7 10]
 [41 32 41 32 39]
 [ 8 24  8 41 13]
 [35 26  8 32  6]]
Shape of mn is:  (4, 5)
Data Type of mn is:  int32
Type of mn is:  <class 'numpy.ndarray'>

Reshaped array nm is:  [[ 9  3 41  7]
 [10 41 32 41]
 [32 39  8 24]
 [ 8 41 13 35]
 [26  8 32  6]]
Shape of nm is:  (5, 4)
Data Type of nm is:  int32
Type of mn is:  <class 'numpy.ndarray'>


In [7]:
# part d.
data_arr= np.array([4,7,'xyz',0,3,'abc',0])
Zero=[]
non_zero=[]
NaN = []

for i in range(len(data_arr)):
    if(data_arr[i].isdigit()):
        if(data_arr[i]=='0'):
            Zero.append(i)
        else:
            non_zero.append(i)
    else:
        NaN.append(i)
        
        
print('Zero elements at indices: ',Zero)
print('Non-Zero elements at indices: ',non_zero)
print('NaN elements at indices: ',NaN)

Zero elements at indices:  [3, 6]
Non-Zero elements at indices:  [0, 1, 4]
NaN elements at indices:  [2, 5]
